### ISSUE TITLE
Restart Spacenet to incorporate FEVM and improvements

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/spacenet#21]
## Background
Since the latest rebase with `filecoin-project/lotus@master`, nodes built from `consensus-shipyard/lotus@spacenet` are no longer able to sync with the current deployment of spacenet, throwing the following error: 
```
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/home/tippyflits/lotus/node/modules/lp2p/addrs.go:85): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build dtypes.NetworkName: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): unknown actor code bafk2bzacebjr3xwsdzfie47rtffibt3irr7a5qqstt7fsbwnolzz3z6oy5frw
```
The reason for this is that the version of the code used for the current deployment (before the latest rebase) used a version of the `v17` actor bundle previous from the mainnet upgrade, and consequently, the cids of the builtin acotrs' code for the current actor bundle is no longer synced with the stable ones for `v17` (and thus the error). Finding the right commit for the bundle version currently used in Spacenet is showing to be harder than expected, so unless someone strongly disagrees, spacenet will be restarted to use the latest stable actor bundle for `v17`. 

Thank you @TippyFlitsUK for catching the bug!

## Workaround
The Spacenet team is having a well-deserved break for the next two weeks, and the deployment upgrade won't land until early January. If in the meantime, if you want to sync and connect to the current Spacenet deployment, run your node from `c2eda3d`, the latest commit that works and is able to sync with Spacenet.

## Release notes
The upgrade will include the following: 
- [x] Rebase with [latest version of `feat/nv18-fevm` ](https://github.com/filecoin-project/lotus/tree/feat/nv18-fevm) to get FEVM support.
  -  https://github.com/consensus-shipyard/lotus/issues/31
- [x] Splitstore enabled in all peers.
- [x] https://github.com/consensus-shipyard/lotus/pull/44
  - This will open the door to onboarding external validators to the network. 
- [x] https://github.com/consensus-shipyard/lotus/pull/46
- [x] New release of Mir with several improvements.
  - https://github.com/filecoin-project/mir/issues/314
- [x] Builtin-actor bundle including IPC actors. 
- [x] Several IPC endpoints.  
## Important reminder
- [x] We need to re-generate the genesis (`spacenet.car`) to support the latest version.

**Comment by adlrocha** [comment]
We should take advantage of the restart to enable the splitstore in all nodes in the deployment: https://github.com/filecoin-project/lotus/tree/master/blockstore/splitstore

**Comment by adlrocha** [comment]
> @adlrocha are the release notes still accurate for the pre-IPC update? I'm guessing probably not (since 4 Jan), so do we have a reference elsewhere?

I've updated the list with a few more items that were recently included. That being said, we want every Spacenet restart to be linked to a specific release from Eudico, which mean that we will include an up-to-date release notes in every release.

**Comment by TippyFlitsUK** [comment]
The Makefile needs a Eudico update - 
```
install -C ./lotus /usr/local/bin/lotus
install: cannot stat './lotus': No such file or directory
make: *** [Makefile:176: install-daemon] Error 1
```

**Comment by TippyFlitsUK** [comment]
I am unable to connect to any peers at the moment.
`eudico version 1.19.1-dev+2k+git.3c1043cdd`
