### ISSUE TITLE
Automate status page

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/spacenet#22]
Automate https://spacenet.statuspage.io/ to monitor the state of each of the services instead of manually having to report downtimes.

**Comment by jsoares** [comment]
Is this something that we're positioned to do these days, with the health monitoring endpoints?

A related suggestion from Johnny was to fold our spacenet status monitoring into the overall [filecoin statuspage](https://status.filecoin.io/), alongside remaining networks. I don't have strong feelings but it's something we should consider/discuss.

**Comment by adlrocha** [comment]
@dnkolegov, would you mind giving some input here? You have better context about what is possible with our current monitoring tools. Thanks!

**Comment by dnkolegov** [comment]
We monitor our services using CloudWatch, which was the fastest solution at that time! It can't be integrated with statuspage as far as I [know](https://community.atlassian.com/t5/Statuspage-questions/Use-CloudWatch-to-monitor-API-health/qaq-p/2135904). To integrate statuspage and monitoring we should use other services like Dtadog.

**Comment by jsoares** [comment]
I don't think we strictly need to use statuspage, but should probably have some publicly visible endpoints. So we could go with something else that had better integration _or_ we can just ask the fil-infra team about querying our endpoints in the same way that they do for other networks -- I'm assuming we're just using pingdom in some quasi-trivial manner, though I might be wrong.
