### ISSUE TITLE
M1 launch comms and community engagement

### ISSUE THREAD

**Issue by jsoares** [consensus-shipyard/spacenet#25]
- Work out social channels and discussion venues
- Schedule community calls
- Define release schedule
- Set up GH templates
- Update ipc.space

**Comment by TippyFlitsUK** [comment]
Added M1 launch plan here - https://docs.google.com/document/d/1nxrDn2ilDQOg6f6WpKmv4Y9kW0-kloaL0xtJwO_RbBs/edit#heading=h.18krzze0qwyc
